name: biocode
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.1
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_sign_in: ^6.3.0
  intl: ^0.19.0
  meta: ^1.15.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.0.15
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/biotics_logo_image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/biotics_logo_image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/biotics_logo_image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/biotics_logo_image.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/svgs/social_media_icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
flutter_intl:
  enabled: true
